### ISSUE TITLE
컴퓨터가 하는 일

### ISSUE THREAD

**Issue by dmstn0526** [shinhan-team-PDA/pig-dice-game#6]
## 요약
컴퓨터는 random 횟수 만큼 주사위 굴리기를 반복한다.
주사위가 1이면 end, end시 bank를 호출한다.

## 할일
- [x] 주사위 굴릴 횟수 random으로 받기
- [x] 주사위 눈이 1이면 should_stop()호출 

## 참조
https://cupola.gettysburg.edu/cgi/viewcontent.cgi?article=1003&context=csfac

**Comment by kji-dec** [comment]
DONE!

**Comment by dmstn0526** [comment]
done
